### ISSUE TITLE
Custom SweetSheetType

### ISSUE THREAD

**Issue by jg-l** [CorneilleEdi/sweetsheet#1]
It would be nice if we can create our own SweetSheetType, or at least define our own colour branding.

**Comment by CorneilleEdi** [comment]
Great idea. I'm working on it for the next release 0.2.0.
Stay tuned

**Comment by jg-l** [comment]
Nice!

If you need contributions,  please let me know. This project is awesome.

**Comment by CorneilleEdi** [comment]
Feel free to contribute.

**Comment by CorneilleEdi** [comment]
Release 0.2.0 with full customisation is out.
Go check it out.
